config/routes.rb
Rails.application.routes.draw do
 
  get 'home/index88'

  resources :pins

    devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  
  get 'home/about'
  
  root 'pins#index'
 

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, :styles => { :medium => "240x300>", :thumb => "50x50>", :normal => "420x680>"  },
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml")
                    
    validates_presence_of :descrption,:image              
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  attr_reader :fullname
  

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,# :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  validates_presence_of :email
  
  has_many :pins , dependent: :destroy
  
  
  def fullname
        "#{self.first_name}  #{self.last_name}"
  end
  
  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          first_name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
       # user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) << :first_name  << :last_name
        devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index88
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)
        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook, :linkedin, :google_oauth2].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
   # if
      resource.email_verified?
      super resource
    #else
     # finish_signup_path(resource)
    #end
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :correct_user, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    
    @pins = Pin.all.order("created_at DESC")
                   .paginate(:page => params[:page], :per_page => 9)
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
       redirect_to @pin , notice: "Pin was successfully created"
    else
      render action: 'new'
    end  
  end

  def update
    @pin.update(pin_params)
    if  @pin.update(pin_params)
        redirect_to @pin , notice: "Pin was successfully created"
    else
      render action: 'edit'
    end  
  end

  def destroy
    @pin.destroy
     redirect_to pins_path
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:descrption,:image)
    end
end

  def correct_user
    @pin =current_user.pins.find(params[:id])
  end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Photo Share",root_path,:class=>"navbar-brand" %>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",root_path %></li>
        <li><%= link_to "About Me",home_about_path %></li>
         <li> <%= link_to "List Pins" , pins_path %></li>
          
        <% if user_signed_in? %>
          <li><%= link_to "Add Pin" ,new_pin_path  %></li>
          <li><%= link_to current_user.fullname ,"#"  %></li>
          <li><%= link_to "Logout" ,destroy_user_session_path,method: :delete  %></li>
          <li><%= link_to "Edit Profile" , edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Login" , new_user_session_path %></li>
          <li><%= link_to "Join" , new_user_registration_path  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_jumbo.html.erb
<div class="jumbotron center">
        <h1>Welcome to My Photo Share App !</h1>
        <p>Preety Cool , Don't you think</p>
         
         <% if user_signed_in? %>
             <%= link_to "Logout" ,destroy_user_session_path,method: :delete, :class=>"btn btn-primary"  %>
             <%= link_to "Edit Profile" , edit_user_registration_path, :class=>"btn btn-default" %>
        <% else %>
             <%= link_to "Login" , new_user_session_path , :class=>"btn btn-default" %>
             <%= link_to "Join" , new_user_registration_path , :class=>"btn btn-primary" %>
        <% end %>
        
</div>

app/views/home/about.html.erb
<h1>My name is Sourav Bhadani</h1>
<p> I am Going to create a Photo Share App</p>

app/views/home/index88.html.erb
<h1>Home#index88</h1>
<p>Find me in app/views/home/index88.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo Share</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, intial-scale=1, maximum-scale=1">
</head>
<body>

<%= render "home/header" %>
<div class="container" >
  
  <% flash.each do | name , msg| %>
      <%= content_tag(:div, msg, class:"alert alert-info") %>
  <% end %>
  
  <%= yield %>
</div>

</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin , :validate => true ,html: { multipart: true } do |f| %>
      <% if @pin.errors.any? %>
        <div id="error_explanation">
          <h2>
              <%= pluralize(@pin.errors.count, "error") %>
              prohibited this pin from being saved:
          </h2>
          <ul>
            <% @pin.errors.full_messages.each do |message| %>
              <li>
                  <%= message %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :descrption %><br>
        <%= f.text_field :descrption, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :image %><br>
        <%= f.file_field :image, class:"form-control" ,style:"display:none",id:"lefile" %>
        
          <div class="input-append",style:"color:red">
          <input id="photoCover" class="input-large" type="text">
          <a class="btn" onclick="$('input[id=lefile]').click();">Browse</a>
          </div>
 

      </div>
      <div class="actions">
        <%= f.submit "Create Pin", :class=>"btn btn-primary" %>
      </div>
<% end %>
<script type="text/javascript">
$('input[id=lefile]').change(function() {
$('#photoCover').val($(this).val());
});
</script>

app/views/pins/edit.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
        <h1>Editing pin</h1>
   </div>
   <div class="panel-body">
        <%= render 'form' %>
    </div>
    <div class="panel-body">
       <%= link_to 'Show', @pin %> |
       <%= link_to 'Back', pins_path %>
    </div>
</div>    
    

app/views/pins/index.html.erb
<%= render "home/jumbo" unless user_signed_in? %>
 <div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
        <div class="box">
            <div class="panel panel-default">
                  <%= link_to image_tag(pin.image.url(:medium)) ,pin%>
               <div class="panel-body">
                    <%= pin.descrption %><br />
                  <strong><%= pin.user.first_name %></strong>    
                </div>
                <% if pin.user == current_user %>
                    <div class="panel-footer">
                        <%= link_to 'Edit', edit_pin_path(pin) %>
                        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                <% end %>
            </div>        
        </div>   
    <% end %>
 </div>
  <div class="center">
 <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
  </div>

app/views/pins/new.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
     <h1>New pin</h1>
   </div>
   <div class="panel-body">
        <%= render 'form' %>
    </div>
    <div class="panel-body">
        <%= link_to 'Back', pins_path %>
    </div>
</div>    
    

app/views/pins/show.html.erb
<div class="row">
     <div class="col-md-offset-2 col-md-8 center">
          <div class="panel panel-default center">
                  <div class="panel-heading ">
                  <%= image_tag  @pin.image.url(:normal)%>
                  </div>
                <div class="panel-body">
                    <%= @pin.descrption %><br />
                  <strong><%= @pin.user.fullname %></strong> <br />   
                <% if @pin.user == current_user %>
                    <%= link_to 'Edit', edit_pin_path(@pin) %>
                 <% end %>  
                    <%= link_to 'Back',pin_path %>
                </div>    
            </div>  
        </div>
    </div>
</div>    